names = [
  ("swadian_name_1", "Gallagus"),
  ("swadian_name_2", "Klargus"),
  ("swadian_name_3", "Mirchaud"),
  ("swadian_name_4", "Richard"),
  ("swadian_name_5", "Thibault"),
  ("swadian_name_6", "Thiel"),
  ("swadian_name_7", "Marcus"),
  ("swadian_name_8", "Charles"),
  ("swadian_name_9", "Romulus"),
  ("swadian_name_10", "Luis"),
  ("swadian_name_11", "Quintilus"),
  ("swadian_name_12", "Edward"),
  ("swadian_name_13", "Salius"),
  ("swadian_name_14", "Gartimer"),
  ("swadian_name_15", "Herald"),
  ("swadian_name_16", "Haringoth"),
  ("swadian_name_17", "Clais"),
  ("swadian_name_18", "Deglan"),
  ("swadian_name_19", "Tredian"),
  ("swadian_name_20", "Grainwad"),
  ("swadian_name_21", "Ryis"),
  ("swadian_name_22", "Plais"),
  ("swadian_name_23", "Stamar"),
  ("swadian_name_24", "Meltor"),
  ("swadian_name_25", "Beranz"),
  ("swadian_name_26", "Rafard"),
  ("swadian_name_27", "Regas"),
  ("swadian_name_28", "Devlian"),
  ("swadian_name_29", "Rafarch"),
  ("swadian_name_30", "Rochabarth"),
  ("swadian_name_31", "Despin"),
  ("swadian_name_32", "Montewar"),
  ("swadian_name_33", "Pechnack"),
  ("swadian_name_34", "Baldur"),
  ("swadian_name_35", "Copart"),
  ("swadian_name_36", "Fouckard"),
  ("swadian_name_37", "Turias"),
  ("swadian_name_38", "Verrier"),
  ("swadian_name_39", "Harlaus"),
  ("swadian_name_40", "Herlard"),
  ("swadian_name_41", "Julius"),
  ("swadian_name_42", "Tulius"),
  ("swadian_name_43", "Julian"),
  ("swadian_name_44", "Kilian"),
  ("swadian_name_45", "Maximilian"),
  ("swadian_name_46", "Maximus"),
  ("swadian_name_47", "Titus"),
  ("swadian_name_48", "Rochard"),
  ("swadian_name_49", "Fochard"),
  ("swadian_name_50", "Michabarth"),
  ("swadian_name_51", "Helad"),
  ("swadian_name_52", "Gerlaus"),
  # ("swadian_name_53", ""),
  # ("swadian_name_54", ""),
  # ("swadian_name_55", ""),
  # ("swadian_name_56", ""),
  # ("swadian_name_57", ""),
  # ("swadian_name_58", ""),
  # ("swadian_name_59", ""),
  # ("swadian_name_60", ""),
  # ("swadian_name_61", ""),
  # ("swadian_name_62", ""),
  # ("swadian_name_63", ""),
  # ("swadian_name_64", ""),
  # ("swadian_name_65", ""),
  # ("swadian_name_66", ""),
  # ("swadian_name_67", ""),
  # ("swadian_name_68", ""),
  # ("swadian_name_69", ""),
  
  ("vaegir_name_1", "Yaroglek"),
  ("vaegir_name_2", "Vuldrat"),
  ("vaegir_name_3", "Naldera"),
  ("vaegir_name_4", "Meriga"),
  ("vaegir_name_5", "Khavel"),
  ("vaegir_name_6", "Doru"),
  ("vaegir_name_7", "Belgaru"),
  ("vaegir_name_8", "Ralcha"),
  ("vaegir_name_9", "Vlan"),
  ("vaegir_name_10", "Mleza"),
  ("vaegir_name_11", "Nelag"),
  ("vaegir_name_12", "Crahask"),
  ("vaegir_name_13", "Bracha"),
  ("vaegir_name_14", "Druli"),
  ("vaegir_name_15", "Marmun"),
  ("vaegir_name_16", "Gastya"),
  ("vaegir_name_17", "Harish"),
  ("vaegir_name_18", "Taisa"),
  ("vaegir_name_19", "Valishin"),
  ("vaegir_name_20", "Rudin"),
  ("vaegir_name_21", "Kumipa"),
  ("vaegir_name_22", "Ralchad"),
  ("vaegir_name_23", "Guro"),
  ("vaegir_name_24", "Opnik"),
  ("vaegir_name_25", "Vuloi"),
  ("vaegir_name_26", "Kobyla"),
  ("vaegir_name_27", "Gottorp"),
  ("vaegir_name_28", "Pasch"),
  ("vaegir_name_29", "Valdym"),
  ("vaegir_name_30", "Dernyek"),
  ("vaegir_name_31", "Vern"),
  ("vaegir_name_32", "Raldym"),
  ("vaegir_name_33", "Igldaf"),
  ("vaegir_name_34", "Aethrod"),
  ("vaegir_name_35", "Geal"),
  ("vaegir_name_36", "Velga"),
  ("vaegir_name_37", "Braga"),
  ("vaegir_name_38", "Marndig"),
  ("vaegir_name_39", "Vaelik"),
  ("vaegir_name_40", "Maerek"),
  ("vaegir_name_41", "Marak"),
  ("vaegir_name_42", "Goraldik"),
  ("vaegir_name_43", "Slavak"),
  ("vaegir_name_44", "Vaerzun"),
  ("vaegir_name_45", "Gulym"),
  ("vaegir_name_46", "Torvald"),
  # ("vaegir_name_47", ""),
  # ("vaegir_name_48", ""),
  # ("vaegir_name_49", ""),
  # ("vaegir_name_50", ""),
  
  ("khergit_name_1", "Sanjar"),
  ("khergit_name_2", "Alagur"),
  ("khergit_name_3", "Tonju"),
  ("khergit_name_4", "Belir"),
  ("khergit_name_5", "Asugan"),
  ("khergit_name_6", "Brula"),
  ("khergit_name_7", "Imirza"),
  ("khergit_name_8", "Urumuda"),
  ("khergit_name_9", "Kramuk"),
  ("khergit_name_10", "Chaurka"),
  ("khergit_name_11", "Sebula"),
  ("khergit_name_12", "Tulug"),
  ("khergit_name_13", "Nasugei"),
  ("khergit_name_14", "Urubay"),
  ("khergit_name_15", "Hugu"),
  ("khergit_name_16", "Tansugai"),
  ("khergit_name_17", "Tirida"),
  ("khergit_name_18", "Ulusamai"),
  ("khergit_name_19", "Karaban"),
  ("khergit_name_20", "Akadan"),
  ("khergit_name_21", "Dundush"),
  ("khergit_name_22", "Khun"),
  ("khergit_name_23", "Liraz"),
  ("khergit_name_24", "Hyun"),
  ("khergit_name_25", "Daman"),
  ("khergit_name_26", "Dustum"),
  ("khergit_name_27", "Saliz"),
  ("khergit_name_28", "Herei"),
  ("khergit_name_29", "Humai"),
  ("khergit_name_30", "Gensis"),
  ("khergit_name_31", "Sangai"),
  ("khergit_name_32", "Aleshtur"),
  ("khergit_name_33", "Manshai"),
  ("khergit_name_34", "Lin"),
  ("khergit_name_35", "Karamir"),
  ("khergit_name_36", "Azrai"),
  ("khergit_name_37", "Hulai"),
  ("khergit_name_38", "Karduk"),
  ("khergit_name_39", "Genshir"),
  ("khergit_name_40", "Shinghis"),
  ("khergit_name_41", "Dunghis"),
  ("khergit_name_42", "Shaghal"),
  ("khergit_name_43", "Kilum"),
  # ("khergit_name_44", ""),
  # ("khergit_name_45", ""),
  # ("khergit_name_46", ""),
  # ("khergit_name_47", ""),
  # ("khergit_name_48", ""),
  # ("khergit_name_49", ""),
  # ("khergit_name_50", ""),
  
  ("nordic_name_1", "Ragnar"),
  ("nordic_name_2", "Lethwin"),
  ("nordic_name_3", "Aedin"),
  ("nordic_name_4", "Irya"),
  ("nordic_name_5", "Olaf"),
  ("nordic_name_6", "Reamald"),
  ("nordic_name_7", "Turya"),
  ("nordic_name_8", "Gundur"),
  ("nordic_name_9", "Harald"),
  ("nordic_name_10", "Knudarr"),
  ("nordic_name_11", "Haeda"),
  ("nordic_name_12", "Turegor"),
  ("nordic_name_13", "Logarson"),
  ("nordic_name_14", "Aeric"),
  ("nordic_name_15", "Faarn"),
  ("nordic_name_16", "Bulba"),
  ("nordic_name_17", "Rayeck"),
  ("nordic_name_18", "Dirigun"),
  ("nordic_name_19", "Marayirr"),
  ("nordic_name_20", "Gearth"),
  ("nordic_name_21", "Surdun"),
  ("nordic_name_22", "Gerlad"),
  ("nordic_name_23", "Thorir"),
  ("nordic_name_24", "Hagar"),
  ("nordic_name_25", "Ingmar"),
  ("nordic_name_26", "Ydnor"),
  ("nordic_name_27", "Rolnack"),
  ("nordic_name_28", "Jorund"),
  ("nordic_name_29", "Jonulf"),
  ("nordic_name_30", "Borg"),
  ("nordic_name_31", "Aelle"),
  ("nordic_name_32", "Bjorn"),
  ("nordic_name_33", "Thorbjorn"),
  ("nordic_name_34", "Harik"),
  ("nordic_name_35", "Horik"),
  ("nordic_name_36", "Hagvar"),
  ("nordic_name_37", "Floki"),
  ("nordic_name_38", "Borgen"),
  ("nordic_name_39", "Jorgen"),
  ("nordic_name_40", "Erik"),
  ("nordic_name_41", "Uldin"),
  ("nordic_name_42", "Uthred"),
  ("nordic_name_43", "Vlok"),
  ("nordic_name_44", "Jorgr"),
  ("nordic_name_45", "Roggvigr"),
  ("nordic_name_46", "Ralofnir"),
  ("nordic_name_47", "Olfigr"),
  ("nordic_name_48", "Rorik"),
  ("nordic_name_49", "Svenr"),
  ("nordic_name_49", "Dvierg"),
  ("nordic_name_50", "Thorbald"),
  
  ("rhodok_name_1", "Graveth"),
  ("rhodok_name_2", "Kastor"),
  ("rhodok_name_3", "Matheas"),
  ("rhodok_name_4", "Gutlans"),
  ("rhodok_name_5", "Laruqen"),
  ("rhodok_name_6", "Raichs"),
  ("rhodok_name_7", "Reland"),
  ("rhodok_name_8", "Tarchias"),
  ("rhodok_name_9", "Gharmall"),
  ("rhodok_name_10", "Talbar"),
  ("rhodok_name_11", "Rimusk"),
  ("rhodok_name_12", "Falsevor"),
  ("rhodok_name_13", "Etrosq"),
  ("rhodok_name_14", "Kurnias"),
  ("rhodok_name_15", "Tellrog"),
  ("rhodok_name_16", "Tribidan"),
  ("rhodok_name_17", "Gerluchs"),
  ("rhodok_name_18", "Fudreim"),
  ("rhodok_name_19", "Nealcha"),
  ("rhodok_name_20", "Fraichin"),
  ("rhodok_name_21", "Trimbau"),
  ("rhodok_name_22", "Reichsin"),
  ("rhodok_name_23", "Jemun"),
  ("rhodok_name_24", "Cirec"),
  ("rhodok_name_25", "Bargas"),
  ("rhodok_name_26", "Holmun"),
  ("rhodok_name_27", "Mandavir"),
  ("rhodok_name_28", "Chalbau"),
  ("rhodok_name_29", "Caenlin"),
  ("rhodok_name_30", "Haidos"),
  ("rhodok_name_31", "Henry"),
  ("rhodok_name_32", "Faendric"),
  ("rhodok_name_33", "Romulus"),
  ("rhodok_name_34", "Robin"),
  ("rhodok_name_35", "Bunduk"),
  ("rhodok_name_36", "Taren"),
  ("rhodok_name_37", "Terans"),
  ("rhodok_name_38", "Turis"),
  ("rhodok_name_39", "Januaq"),
  ("rhodok_name_40", "Teobaq"),
  # ("rhodok_name_41", ""),
  # ("rhodok_name_42", ""),
  # ("rhodok_name_43", ""),
  # ("rhodok_name_44", ""),
  # ("rhodok_name_45", ""),
  # ("rhodok_name_46", ""),
  # ("rhodok_name_47", ""),
  # ("rhodok_name_48", ""),
  # ("rhodok_name_49", ""),
  # ("rhodok_name_50", ""),
  
  ("sarranid_name_1", "Hakim"),
  ("sarranid_name_2", "Uqais"),
  ("sarranid_name_3", "Hamezan"),
  ("sarranid_name_4", "Atis"),
  ("sarranid_name_5", "Nuwas"),
  ("sarranid_name_6", "Mundhalir"),
  ("sarranid_name_7", "Ghanawa"),
  ("sarranid_name_8", "Nuam"),
  ("sarranid_name_9", "Dhiyul"),
  ("sarranid_name_10", "Lakhem"),
  ("sarranid_name_11", "Ghulassen"),
  ("sarranid_name_12", "Azadun"),
  ("sarranid_name_13", "Quryas"),
  ("sarranid_name_14", "Amdar"),
  ("sarranid_name_15", "Hiwan"),
  ("sarranid_name_16", "Muhnir"),
  ("sarranid_name_17", "Ayyam"),
  ("sarranid_name_18", "Raddoun"),
  ("sarranid_name_19", "Tilimsan"),
  ("sarranid_name_20", "Dhashwal"),
  ("sarranid_name_21", "Biliya"),
  ("sarranid_name_22", "Shabn"),
  ("sarranid_name_23", "Hildalir"),
  ("sarranid_name_24", "Sanshub"),
  ("sarranid_name_25", "Ughaln"),
  ("sarranid_name_26", "Waldin"),
  ("sarranid_name_27", "Dulya"),
  ("sarranid_name_28", "Jiahem"),
  ("sarranid_name_29", "Halmir"),
  ("sarranid_name_30", "Mashkir"),
  ("sarranid_name_31", "Abdal"),
  ("sarranid_name_32", "Dhiwas"),
  ("sarranid_name_33", "Dahwis"),
  ("sarranid_name_34", "Wilahir"),
  ("sarranid_name_35", "Ghulamir"),
  ("sarranid_name_36", "Tiliri"),
  ("sarranid_name_37", "Dugwal"),
  # ("sarranid_name_38", ""),
  # ("sarranid_name_39", ""),
  # ("sarranid_name_40", ""),
  # ("sarranid_name_41", ""),
  # ("sarranid_name_42", ""),
  # ("sarranid_name_43", ""),
  # ("sarranid_name_44", ""),
  # ("sarranid_name_45", ""),
  # ("sarranid_name_46", ""),
  # ("sarranid_name_47", ""),
  # ("sarranid_name_48", ""),
  # ("sarranid_name_49", ""),
  # ("sarranid_name_50", ""),
  
  ("names_end", "NAMES_END"),

  ("swadian_family_name_template_1", "dey {s10}"),
  ("vaegir_family_name_template_1", "{s10}oving"),
  ("khergit_family_name_template_1", "{s10}it"),
  ("nord_family_name_template_1", "{s10}"),
  ("nord_family_name_template_2", "{s10}son"),
  ("rhodok_family_name_template_1", "{s10}"),
  ("sarranid_family_name_template_1", "Banu {s10}"),
  ("mercenary_family_name_template_1", "{s10}"),

  ("family_name_template_end", "FAMILY_NAMES_END"),

  ("swadian_family_name_prefix_1", "Val"),
  ("swadian_family_name_prefix_2", "Cort"),
  ("swadian_family_name_prefix_3", "Gunr"),
  ("swadian_family_name_prefix_4", "Fort"),
  ("swadian_family_name_prefix_5", "Mol"),
  ("swadian_family_name_prefix_6", "Jel"),
  ("swadian_family_name_prefix_7", "Folc"),
  ("swadian_family_name_prefix_8", "Roth"),
  ("swadian_family_name_prefix_9", "Mer"),
  ("swadian_family_name_prefix_10", "Arrom"),

  ("swadian_family_name_suffix_1", "ant"),
  ("swadian_family_name_suffix_2", "ain"),
  ("swadian_family_name_suffix_3", "ic"),
  ("swadian_family_name_suffix_4", "es"),
  ("swadian_family_name_suffix_5", "arn"),
  ("swadian_family_name_suffix_6", "ind"),
  ("swadian_family_name_suffix_7", "un"),
  ("swadian_family_name_suffix_8", "ad"),
  ("swadian_family_name_suffix_9", "oc"),
  ("swadian_family_name_suffix_10", "anc"),

  ("vaegir_family_name_prefix_1", "Gund"),
  ("vaegir_family_name_prefix_2", "Kul"),
  ("vaegir_family_name_prefix_3", "Vag"),
  ("vaegir_family_name_prefix_4", "Orm"),
  ("vaegir_family_name_prefix_5", "Tog"),
  ("vaegir_family_name_prefix_6", "Is"),
  ("vaegir_family_name_prefix_7", "Isy"),
  ("vaegir_family_name_prefix_8", "Vezh"),
  ("vaegir_family_name_prefix_9", "Ubr"),
  ("vaegir_family_name_prefix_10", "Kost"),

  ("vaegir_family_name_suffix_1", "ar"),
  ("vaegir_family_name_suffix_2", "yor"),
  ("vaegir_family_name_suffix_3", "ir"),
  ("vaegir_family_name_suffix_4", "id"),
  ("vaegir_family_name_suffix_5", "yar"),
  ("vaegir_family_name_suffix_6", "or"),

  ("khergit_family_name_prefix_1", "Urkh"),
  ("khergit_family_name_prefix_2", "Kh"),
  ("khergit_family_name_prefix_3", "Ark"),
  ("khergit_family_name_prefix_4", "Tig"),
  ("khergit_family_name_prefix_5", "Har"),
  ("khergit_family_name_prefix_6", "Balt"),
  ("khergit_family_name_prefix_7", "Kolt"),
  ("khergit_family_name_prefix_8", "Yan"),
  ("khergit_family_name_prefix_9", "Ob"),
  ("khergit_family_name_prefix_10", "Karakh"),
  ("khergit_family_name_prefix_11", "Khar"),

  ("khergit_family_name_suffix_1", "una"),
  ("khergit_family_name_suffix_2", "erg"),
  ("khergit_family_name_suffix_3", "un"),
  ("khergit_family_name_suffix_4", "r"),
  ("khergit_family_name_suffix_5", "f"),
  ("khergit_family_name_suffix_6", "a"),
  ("khergit_family_name_suffix_7", "ser"),
  ("khergit_family_name_suffix_8", "u"),

  ("nord_family_name_prefix_1", "Hairy"),
  ("nord_family_name_prefix_2", "Sweaty"),
  ("nord_family_name_prefix_3", "Strong"),
  ("nord_family_name_prefix_4", "Bold"),
  ("nord_family_name_prefix_5", "Feeble"),
  ("nord_family_name_prefix_6", "Fiery"),
  ("nord_family_name_prefix_7", "Red"),
  ("nord_family_name_prefix_8", "Grey"),
  ("nord_family_name_prefix_9", "White"),
  ("nord_family_name_prefix_10", "Dark"),
  ("nord_family_name_prefix_11", "Great"),
  ("nord_family_name_prefix_12", "Bald"),
  ("nord_family_name_prefix_13", "Bear"),
  ("nord_family_name_prefix_14", "Howling"),
  ("nord_family_name_prefix_15", "Sleek"),
  ("nord_family_name_prefix_16", "Long"),
  ("nord_family_name_prefix_17", "Short"),
  ("nord_family_name_prefix_18", "Giant"),
  ("nord_family_name_prefix_19", "Oaken"),
  ("nord_family_name_prefix_20", "Stone"),
  ("nord_family_name_prefix_21", "Wide"),
  ("nord_family_name_prefix_22", "Far"),
  ("nord_family_name_prefix_23", "Swift"),
  ("nord_family_name_prefix_24", "Sharp"),

  ("nord_family_name_suffix_1", "-Breeks"),
  ("nord_family_name_suffix_2", "-Arms"),
  ("nord_family_name_suffix_3", "-Hands"),
  ("nord_family_name_suffix_4", "-Palm"),
  ("nord_family_name_suffix_5", "-Beard"),
  ("nord_family_name_suffix_6", "-Mane"),
  ("nord_family_name_suffix_7", "-Shield"),
  ("nord_family_name_suffix_8", "-Raven"),
  ("nord_family_name_suffix_9", "-Neck"),
  ("nord_family_name_suffix_10", "-Drink"),
  ("nord_family_name_suffix_11", "-Breath"),
  ("nord_family_name_suffix_12", "-Legs"),
  ("nord_family_name_suffix_13", "-Voice"),
  ("nord_family_name_suffix_14", "-Eyes"),
  ("nord_family_name_suffix_15", "-Ears"),
  ("nord_family_name_suffix_16", "-Teeth"),
  ("nord_family_name_suffix_17", "-Axe"),
  ("nord_family_name_suffix_18", "-Gale"),
  ("nord_family_name_suffix_19", "-Helm"),
  ("nord_family_name_suffix_20", "-Feet"),
  ("nord_family_name_suffix_21", "-Wits"),

  ("rhodok_family_name_prefix_1", "Viz"),
  ("rhodok_family_name_prefix_2", "Chor"),
  ("rhodok_family_name_prefix_3", "Hung"),
  ("rhodok_family_name_prefix_4", "Pethr"),
  ("rhodok_family_name_prefix_5", "Dol"),
  ("rhodok_family_name_prefix_6", "Jul"),
  ("rhodok_family_name_prefix_7", "Phal"),
  ("rhodok_family_name_prefix_8", "Rothr"),
  ("rhodok_family_name_prefix_9", "Ner"),
  ("rhodok_family_name_prefix_10", "Avom"),

  ("rhodok_family_name_suffix_1", "antes"),
  ("rhodok_family_name_suffix_2", "enios"),
  ("rhodok_family_name_suffix_3", "ios"),
  ("rhodok_family_name_suffix_4", "es"),
  ("rhodok_family_name_suffix_5", "ardes"),
  ("rhodok_family_name_suffix_6", "anis"),
  ("rhodok_family_name_suffix_7", "onos"),
  ("rhodok_family_name_suffix_8", "ides"),
  ("rhodok_family_name_suffix_9", "icos"),
  ("rhodok_family_name_suffix_10", "entos"),
  ("rhodok_family_name_suffix_11", "entes"),
  ("rhodok_family_name_suffix_12", "onis"),

  ("sarranid_family_name_prefix_1", "Huly"),
  ("sarranid_family_name_prefix_2", "Sarr"),
  ("sarranid_family_name_prefix_3", "Qil"),
  ("sarranid_family_name_prefix_4", "Qar"),
  ("sarranid_family_name_prefix_5", "Arb"),
  ("sarranid_family_name_prefix_6", "At"),
  ("sarranid_family_name_prefix_7", "Sarm"),
  ("sarranid_family_name_prefix_8", "Sar"),
  ("sarranid_family_name_prefix_9", "Habb"),
  ("sarranid_family_name_prefix_10", "Ruw"),
  ("sarranid_family_name_prefix_11", "Jaw"),
  ("sarranid_family_name_prefix_12", "Ghilm"),
  ("sarranid_family_name_prefix_13", "Zil"),

  ("sarranid_family_name_suffix_1", "an"),
  ("sarranid_family_name_suffix_2", "d"),
  ("sarranid_family_name_suffix_3", "az"),
  ("sarranid_family_name_suffix_4", "as"),
  ("sarranid_family_name_suffix_5", "al"),
  ("sarranid_family_name_suffix_6", "ij"),
  ("sarranid_family_name_suffix_7", "ab"),
  ("sarranid_family_name_suffix_8", "aid"),

  ("family_name_end", "end"),

]
