name: Build project

on: 
  pull_request:
    branches:
      - 'main'
    types:
      - closed

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v4

    - name: Create output directory
      run: mkdir Output
    
    - name: Replace string in file
      uses: thiagodnf/string-replacer@v1.0.2
      with:
        find: 'export_dir = .*$'
        replace: 'export_dir = "..\Output/"'
        include: 'Src/module_info.py'
        
    - name: setup python 2.7.13
      uses: LizardByte/setup-python-action@master
      with:
        python-version: '2.7'
        
    - name: Run bat file
      working-directory: ./Src
      run: ./build_module.bat
      
    - name: Create Resources directory
      working-directory: ./Output
      run: mkdir Resource
      
    - name: Create Textures directory
      working-directory: ./Output
      run: mkdir Textures
      
    - name: Create SceneObj directory
      working-directory: ./Output
      run: mkdir SceneObj
      
    - name: Copy module.ini
      run: Copy-Item ./Res/module.ini -Destination ./Output
      
    - name: Extract resources
      run: Expand-Archive -Path ./Res/Resource.zip -DestinationPath ./Output/Resource
      
    - name: Extract textures
      run: Expand-Archive -Path ./Res/Textures.zip -DestinationPath ./Output/Textures
      
    - name: Extract sceneobj
      run: Expand-Archive -Path ./Res/scenes.zip -DestinationPath ./Output/SceneObj

    - name: Create archive
      run: Compress-Archive -Path ./Output -DestinationPath ./Output.zip

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.head_ref }}-r
        artifacts: ./Output.zip
