name: Build project

on: 
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v4
    - name: setup python 2.7.13
      uses: LizardByte/setup-python-action@master
      with:
        python-version: '2.7.13'
    - name: Replace string in file
      uses: MathieuSoysal/replace-string-in-file@v1.0.0
      with:
        file: ./Src/build_module.bat
        old-string: 'export_dir = *$'
        new-string: 'export_dir = .\Output/'
    - name: Run bat file
      run: ./Src/build_module.bat
