name: Build project

on: 
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v4
    
    - name: Replace string in file
      uses: thiagodnf/string-replacer@v1.0.2
      with:
        find: "export_dir = *$"
        replace: "export_dir = .\\Output/"
        include: "Src/build_module.bat"
        
    - name: setup python 2.7.13
      uses: LizardByte/setup-python-action@master
      with:
        python-version: '2.7'
        
    - name: Run bat file
      run: ./Src/build_module.bat
