name: Build project

on: 
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 1

    steps:
    - uses: actions/checkout@v4

    - name: Create output directory
      run: mkdir Output
    
    - name: Replace string in file
      uses: thiagodnf/string-replacer@v1.0.2
      with:
        find: 'export_dir = .*$'
        replace: 'export_dir = "..\Output/"'
        include: 'Src/module_info.py'
        
    - name: setup python 2.7.13
      uses: LizardByte/setup-python-action@master
      with:
        python-version: '2.7'
        
    - name: Run bat file
      working-directory: ./Src
      run: ./build_module.bat

    - uses: actions/upload-artifact@v4
      with:
        path: ./Output
        if-no-files-found: error

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
